// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://demfuswhrklpimxgobkf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRlbWZ1c3docmtscGlteGdvYmtmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQ0ODMxOTMsImV4cCI6MjA4MDA1OTE5M30.Ywj1_2XfmwXBIUOYdtVP5FrCea8ZDE1f7UmZH04SQSI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
