// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xqlqdpbtvgkqylyxfidz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhxbHFkcGJ0dmdrcXlseXhmaWR6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwODM3OTYsImV4cCI6MjA2NjY1OTc5Nn0.VzJveosuHdqqlLr7ES2gRImoAuGSYUByi20OJEo737U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);